// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void small_p_Animation( lv_obj_t *TargetObject, int delay);
void large_p_Animation( lv_obj_t *TargetObject, int delay);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
void ui_event_TextArea4( lv_event_t * e);
lv_obj_t *ui_TextArea4;
lv_obj_t *ui_Button3;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
void ui_event_TextArea3( lv_event_t * e);
lv_obj_t *ui_TextArea3;
void ui_event_TextArea1( lv_event_t * e);
lv_obj_t *ui_TextArea1;
void ui_event_TextArea2( lv_event_t * e);
lv_obj_t *ui_TextArea2;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_Switch4;
lv_obj_t *ui_Switch1;
lv_obj_t *ui_Switch2;
void ui_event_Keyboard1( lv_event_t * e);
lv_obj_t *ui_Keyboard1;
lv_obj_t *ui_Screen2;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Button6;
lv_obj_t *ui_Button7;
lv_obj_t *ui_Screen3;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Button9;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bg[1] = {&ui_img_bg1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void small_p_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 250);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_0, 480, 240 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void large_p_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_0, 240, 480 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_TextArea4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      change_size( e );
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 1000, 0);
}
}
void ui_event_TextArea3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      change_size( e );
}
}
void ui_event_TextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      change_size( e );
}
}
void ui_event_TextArea2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      change_size( e );
      small_p_Animation(ui_Panel1, 0);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      large_p_Animation(ui_Panel1, 0);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 0);
}
}
void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 800);
lv_obj_set_height( ui_Panel1, 240);

ui_TextArea4 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextArea4, 173);
lv_obj_set_height( ui_TextArea4, 41);
lv_obj_set_x( ui_TextArea4, -38 );
lv_obj_set_y( ui_TextArea4, 295 );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_TextArea4,"TIME");
lv_obj_clear_flag( ui_TextArea4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button3 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 40);
lv_obj_set_x( ui_Button3, -157 );
lv_obj_set_y( ui_Button3, 367 );
lv_obj_set_align( ui_Button3, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Button1, 218);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 239 );
lv_obj_set_y( ui_Button1, 371 );
lv_obj_set_align( ui_Button1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextArea3 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextArea3, 173);
lv_obj_set_height( ui_TextArea3, 41);
lv_obj_set_x( ui_TextArea3, -275 );
lv_obj_set_y( ui_TextArea3, 295 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_TextArea3,"LOACTION");
lv_obj_clear_flag( ui_TextArea3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextArea1 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextArea1, 411);
lv_obj_set_height( ui_TextArea1, 41);
lv_obj_set_x( ui_TextArea1, -158 );
lv_obj_set_y( ui_TextArea1, 228 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_TextArea1,"API KEY");
lv_obj_clear_flag( ui_TextArea1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextArea2 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextArea2, 240);
lv_obj_set_height( ui_TextArea2, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextArea2, -241 );
lv_obj_set_y( ui_TextArea2, 109 );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_TextArea2,"PASSWORD");
lv_textarea_set_one_line(ui_TextArea2,true);
lv_textarea_set_password_mode(ui_TextArea2, true);
lv_obj_clear_flag( ui_TextArea2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 40);
lv_obj_set_x( ui_Button2, -19 );
lv_obj_set_y( ui_Button2, 114 );
lv_obj_set_align( ui_Button2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Panel1,1000,90);
lv_obj_set_width( ui_Spinner1, 80);
lv_obj_set_height( ui_Spinner1, 80);
lv_obj_set_x( ui_Spinner1, -12 );
lv_obj_set_y( ui_Spinner1, 7 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Dropdown1 = lv_dropdown_create(ui_Panel1);
lv_dropdown_set_text( ui_Dropdown1, "selset wifi");
lv_obj_set_width( ui_Dropdown1, 240);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, -247 );
lv_obj_set_y( ui_Dropdown1, 20 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Switch4 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_Switch4, 50);
lv_obj_set_height( ui_Switch4, 25);
lv_obj_set_x( ui_Switch4, 150 );
lv_obj_set_y( ui_Switch4, 300 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_TOP_MID );

ui_Switch1 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_x( ui_Switch1, 150 );
lv_obj_set_y( ui_Switch1, 200 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_TOP_MID );

ui_Switch2 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_Switch2, 50);
lv_obj_set_height( ui_Switch2, 25);
lv_obj_set_x( ui_Switch2, 150 );
lv_obj_set_y( ui_Switch2, 100 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_TOP_MID );

ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
lv_obj_set_width( ui_Keyboard1, 800);
lv_obj_set_height( ui_Keyboard1, 240);

lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 100);
lv_obj_set_x( ui_Button5, -144 );
lv_obj_set_y( ui_Button5, -81 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 100);
lv_obj_set_x( ui_Button4, 84 );
lv_obj_set_y( ui_Button4, 66 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button6 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 100);
lv_obj_set_x( ui_Button6, 85 );
lv_obj_set_y( ui_Button6, -85 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button7, 100);
lv_obj_set_height( ui_Button7, 100);
lv_obj_set_x( ui_Button7, -143 );
lv_obj_set_y( ui_Button7, 64 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Screen3, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_Screen3, 150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button9 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button9, 100);
lv_obj_set_height( ui_Button9, 50);
lv_obj_set_x( ui_Button9, 194 );
lv_obj_set_y( ui_Button9, 118 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
