// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void small_p_Animation( lv_obj_t *TargetObject, int delay);
void large_p_Animation( lv_obj_t *TargetObject, int delay);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
void ui_event_TextArea4( lv_event_t * e);
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_Button3;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_TextArea3( lv_event_t * e);
extern lv_obj_t *ui_TextArea3;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
void ui_event_TextArea2( lv_event_t * e);
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Switch4;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Switch2;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Screen2;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Screen3;
void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_bg1_png);   // assets\bg1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
